#!/bin/bash -eux
# This has to run at container start (and not as part of the build) because we
# mount in the database secret at run-time.
#
# Note also that symlinks do not work in the RT_SiteConfig.d directory.
cp /opt/share/secrets/rt/rt-db /etc/request-tracker4/RT_SiteConfig.d/98-ocfdb
cp /opt/share/secrets/rt/rt.keytab /tmp/rt.keytab
chown www-data:root /tmp/rt.keytab
exec apachectl -d /etc/apache2 -f apache2.conf -e info -DFOREGROUND
