#!/bin/bash -eux

sed -ri '/^user[ \t]+=/ { s/mysql/root/ }' /etc/mysql/mariadb.conf.d/50-server.cnf

mkdir -p /var/run/mysqld
mysqld &
sleep 10

rt-setup-database --action init --dba root --dba-password ''

killall mysqld
wait
